name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for reporting this issue. Will get back to you if I need more details. Thank Again - Purvik Rana.'
        pr-message: 'Thank you for your contribution to SwipeTo Flutter Package - Purvik Rana.'
